# This Blueprint defines all the services for the 'codecart' application.

services:
  # 1. The PostgreSQL Database
  - type: databases
    name: codecart-db
    plan: free
    databaseName: codecart_db
    user: codecart_user

  # 2. The Python Backend (Web Service)
  - type: web
    name: codecart-backend
    runtime: python
    plan: free
    rootDir: backend # Specifies that the backend code is in the 'backend' folder
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn -w 4 -k uvicorn.workers.UvicornWorker main:app"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: codecart-db # Links to the database defined above
          property: connectionString # Injects the database connection URL
      # --- IMPORTANT: Set these secret values in the Render Dashboard after deploying ---
      - key: ADMIN_EMAIL
        sync: false # 'sync: false' means this value must be set in the dashboard
      - key: ADMIN_PASSWORD
        sync: false

  # 3. The React Frontend (Static Site)
  - type: static
    name: codecart-frontend
    rootDir: frontend # Specifies that the frontend code is in the 'frontend' folder
    buildCommand: "npm install && npm run build"
    publishDir: "dist" # The folder where Vite places the built files
    envVars:
      - key: NODE_VERSION
        value: 20.11.0
      - key: VITE_API_URL
        fromService: # Links this variable to the backend service
          type: web
          name: codecart-backend
          property: url # Injects the live URL of the backend service